<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Koor extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Koordiantor');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'koor/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'koor/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'koor/index.html';
            $config['first_url'] = base_url() . 'koor/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Koordiantor->total_rows($q);
        $koor = $this->Koordiantor->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'koor_data' => $koor,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('koor/user_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Koordiantor->get_by_id($id);
        if ($row) {
            $data = array(
		'ID' => $row->ID,
		'username' => $row->username,
		'password' => $row->password,
	    );
            $this->load->view('koor/user_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('koor'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('koor/create_action'),
	    'ID' => set_value('ID'),
	    'username' => set_value('username'),
	    'password' => set_value('password'),
	);
        $this->load->view('koor/user_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'username' => $this->input->post('username',TRUE),
		'password' => $this->input->post('password',TRUE),
	    );

            $this->Koordiantor->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('koor'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Koordiantor->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('koor/update_action'),
		'ID' => set_value('ID', $row->ID),
		'username' => set_value('username', $row->username),
		'password' => set_value('password', $row->password),
	    );
            $this->load->view('koor/user_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('koor'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('ID', TRUE));
        } else {
            $data = array(
		'username' => $this->input->post('username',TRUE),
		'password' => $this->input->post('password',TRUE),
	    );

            $this->Koordiantor->update($this->input->post('ID', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('koor'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Koordiantor->get_by_id($id);

        if ($row) {
            $this->Koordiantor->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('koor'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('koor'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('username', 'username', 'trim|required');
	$this->form_validation->set_rules('password', 'password', 'trim|required');

	$this->form_validation->set_rules('ID', 'ID', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Koor.php */
/* Location: ./application/controllers/Koor.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-01 07:21:43 */
/* http://harviacode.com */