<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Laporan_files extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Files_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'laporan_files/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'laporan_files/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'laporan_files/index.html';
            $config['first_url'] = base_url() . 'laporan_files/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Files_model->total_rows($q);
        $laporan_files = $this->Files_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'laporan_files_data' => $laporan_files,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('laporan_files/laporan_files_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Files_model->get_by_id($id);
        if ($row) {
            $data = array(
		'NIM' => $row->NIM,
		'url' => $row->url,
	    );
            $this->load->view('laporan_files/laporan_files_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('laporan_files'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('laporan_files/create_action'),
	    'NIM' => set_value('NIM'),
	    'url' => set_value('url'),
	);
        $this->load->view('laporan_files/laporan_files_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'NIM' => $this->input->post('NIM',TRUE),
		'url' => $this->input->post('url',TRUE),
	    );

            $this->Files_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('laporan_files'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Files_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('laporan_files/update_action'),
		'NIM' => set_value('NIM', $row->NIM),
		'url' => set_value('url', $row->url),
	    );
            $this->load->view('laporan_files/laporan_files_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('laporan_files'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('', TRUE));
        } else {
            $data = array(
		'NIM' => $this->input->post('NIM',TRUE),
		'url' => $this->input->post('url',TRUE),
	    );

            $this->Files_model->update($this->input->post('', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('laporan_files'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Files_model->get_by_id($id);

        if ($row) {
            $this->Files_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('laporan_files'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('laporan_files'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('NIM', 'nim', 'trim|required');
	$this->form_validation->set_rules('url', 'url', 'trim|required');

	$this->form_validation->set_rules('', '', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Laporan_files.php */
/* Location: ./application/controllers/Laporan_files.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-05-04 10:20:42 */
/* http://harviacode.com */