<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mahasiswa_model extends CI_Model
{

    public $table = 'mahasiswa';
    public $id = 'NIM';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }





    function get_by_id()
    {
        $this->db->select("mahasiswa.Nama, mahasiswa.No_telp, mahasiswa.NIM, mahasiswa.Angkatan, mahasiswa.JudulProposal,
            user.email, user.password, magang.MulaiMagang, magang.SelesaiMagang, magang.Divisi"); 
        $this->db->from('mahasiswa');
        $this->db->join('user','user.idUser=mahasiswa.idUser');
        $this->db->join('magang','magang.NIM=mahasiswa.NIM');
        $this->db->where('mahasiswa.NIM=14115050');
        $query = $this->db->get();
        return $query->result();
    }
     //tampil data pembimbing dosen
    function tampilDosen(){
        // $this->db->select("*");
        // $this->db->from('pembimbingdosen');
        // $query = $this->db->get();
        // return $query->result();
        return $this->db->get('pembimbingdosen')->result();
    }





    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('NIM', $q);
	$this->db->or_like('idUser', $q);
	$this->db->or_like('idLogbook', $q);
	$this->db->or_like('Nama', $q);
	$this->db->or_like('IPK', $q);
	$this->db->or_like('SKS', $q);
	$this->db->or_like('Angkatan', $q);
	$this->db->or_like('JudulProposal', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('NIM', $q);
	$this->db->or_like('idUser', $q);
	$this->db->or_like('idLogbook', $q);
	$this->db->or_like('Nama', $q);
	$this->db->or_like('IPK', $q);
	$this->db->or_like('SKS', $q);
	$this->db->or_like('Angkatan', $q);
	$this->db->or_like('JudulProposal', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    function update_profil($Nama,$No_telp){
        $NIM = 14115050;
        $data = array(
            'Nama'      => $Nama,
            'No_telp'   => $No_telp,
        );
        $this->db->where('NIM', $NIM);
        $this->db->update('mahasiswa', $data);  
        redirect('Mahasiswa/Profil');
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

   

}

/* End of file Mahasiswa_model.php */
/* Location: ./application/models/Mahasiswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-08 02:47:42 */
/* http://harviacode.com */