<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mahasiswa_model extends CI_Model
{

    public $table = 'mahasiswa';
    public $id = 'NIM';
    public $idUser = 'idUser';
    public $order = 'DESC';
    public $email = 'email';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    public function getDataDiri()
    {
        $this->db->select("*"); 
        $this->db->from('mahasiswa');
        $this->db->join('user','user.idUser=mahasiswa.idUser');
        $this->db->join('magang','magang.NIM=mahasiswa.NIM');
        $this->db->where('mahasiswa.NIM=14115050');
        $query = $this->db->get();
        return $query->result();
    }
    function tampilDosen(){
        return $this->db->get('pembimbingdosen')->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

     function get_by_email($email)
    {
        $this->db->where($this->email, $email);
        return $this->db->get($this->table)->row();
    }
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('NIM', $q);
	$this->db->or_like('idUser', $q);
	$this->db->or_like('idLogbook', $q);
	$this->db->or_like('Nama', $q);
	$this->db->or_like('IPK', $q);
	$this->db->or_like('SKS', $q);
	$this->db->or_like('Angkatan', $q);
	$this->db->or_like('JudulProposal', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('NIM', $q);
	$this->db->or_like('idUser', $q);
	$this->db->or_like('idLogbook', $q);
	$this->db->or_like('Nama', $q);
	$this->db->or_like('IPK', $q);
	$this->db->or_like('SKS', $q);
	$this->db->or_like('Angkatan', $q);
	$this->db->or_like('JudulProposal', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($idUser, $data)
    {
        $this->db->where($this->id, $idUser);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($email)
    {
        $this->db->where($this->email, $email);
        $this->db->delete($this->table);
    }

    public function getNim($nama)
    {
        $this->db->select("*");
        $this->db->from('mahasiswa');
        $this->db->where('Nama = "'.$nama.'"');
        $query = $this->db->get();
        return $query->result();
    }
    public function getNama($nim)
    {
        $this->db->select("*");
        $this->db->from('mahasiswa');
        $this->db->where('Nim = "'.$nim.'"');
        $query = $this->db->get();
        return $query->result();
    }
    public function getNimEmail()
    {
        $this->db->select("*");
        $this->db->from('mahasiswa');
        $this->db->where('email = "'. $this->session->userdata('email').'"');
        $query = $this->db->get();
        return $query->result();
    }
    public function mhskp()
    {
        $this->db->select('*');
        $this->db->from('mahasiswa');
        $this->db->join('magang','mahasiswa.NIM = magang.nim','left');
        $this->db->join('tempatkerja','magang.idPerusahaan = magang.idPerusahaan','left');
        $query = $this->db->get();
        return $query->result();
    }

    public function seminar($data)
    {
         $this->db->set($data);
        $this->db->insert('jadwalseminar', $data);
    }
}

/* End of file Mahasiswa_model.php */
/* Location: ./application/models/Mahasiswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-08 02:47:42 */
/* http://harviacode.com */