<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pembimbingdosen_model extends CI_Model
{

    public $table = 'pembimbingdosen';
    public $id = 'NIP';
    public $order = 'DESC';
    public $idUser = 'idUser';
    public $email = 'email';
    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('NIP', $q);
	$this->db->or_like('idUser', $q);
	$this->db->or_like('Nama', $q);
	$this->db->or_like('Spesialisasi', $q);
	$this->db->or_like('kontak', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('NIP', $q);
	$this->db->or_like('idUser', $q);
	$this->db->or_like('Nama', $q);
	$this->db->or_like('Spesialisasi', $q);
	$this->db->or_like('kontak', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->idUser, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($email)
    {
        $this->db->where($this->email, $email);
        $this->db->delete($this->table);
    }

}

/* End of file Pembimbingdosen_model.php */
/* Location: ./application/models/Pembimbingdosen_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-07 14:25:03 */
/* http://harviacode.com */